on:
  push:

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
        ignore: path.sh cmd.sh
      env:
        SHELLCHECK_OPTS: -x -e SC2086 -e SC1091 -e SC1090